sudo: required
services:
    - docker
script:
    - docker build -t mnsdesigns/node .
    - docker images mnsdesigns/node

before_deploy:
    -docker login -u mnsbutterfly -p inthemiddle#11

deploy:
    provider: script
    script: docker push mnsdesigns/node
    on:
        branch: master