sudo: required
services:
    - docker
script:
    - docker build -t mnsbutterfly/node .
    - docker images mnsbutterfly/node

before_deploy:
    -docker login --username mnsbutterfly --password inthemiddle#11

deploy:
    provider: script
    script: docker push mnsbutterfly/node
    on:
        branch: master